name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'miftah_mobile/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        working-directory: ./miftah_mobile
        run: flutter pub get

      - name: Build Web
        working-directory: ./miftah_mobile
        run: flutter build web --release --base-href "/-miftah-alumni/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./miftah_mobile/build/web
